### ISSUE TITLE
verbose mode did not print all the body text of requests

### ISSUE THREAD

**Issue by kaala** [Orange-OpenSource/hurl#2755] opened 2024-04-30 13:11 UTC
### What is the current *bug* behavior?

I have a hurl file with 3 requests, and I use --verbose command line options.
I expect I can see all the response body for the 3 requests, but verbose mode only prints the response body byte size, and only the last one print the body text.

### Steps to reproduce

prepare a hurl file with many requests in it, and run the file use hurl --verbose file.hurl

### What is the expected *correct* behavior?

I expect all requests output the response body text.

### Execution context

- Hurl Version (`hurl --version`):
hurl 4.3.0 (Windows) libcurl/8.4.0-DEV Schannel zlib/1.3 nghttp2/1.58.0
Features (libcurl):  alt-svc AsynchDNS HSTS HTTP2 IPv6 Largefile libz NTLM SPNEGO SSL SSPI Unicode UnixSockets
Features (built-in): brotli

### Possible fixes

 
![image](https://github.com/Orange-OpenSource/hurl/assets/246542/3236ec13-bd41-43e4-9b51-23cd565c6f69)

**Comment by jcamiel** [comment] 2024-04-30 13:51
Hi @kaala 

This is the intended design of [`--verbose` option](https://hurl.dev/docs/manual.html#verbose). You can use [`--very-verbose`](https://hurl.dev/docs/manual.html#very-verbose) to see all response bodies __on standard error__.

Wether you use or not `--verbose`/`--very-verbose`, the last response body is printed on standard output (once again by design).

**Comment by kaala** [comment] 2024-05-03 09:41
ok, then. could you tell me more about the reason behind this design?

**Comment by jcamiel** [comment] 2024-05-04 13:56
Sure, the idea is to be able to chain request to get data. The typical use cas is getting data behind a login:

```hurl
POST http://foo.com/login
[FormParams]
username: bob
password: secret
HTTP 302

GET http://foo.com/protected
HTTP 200
```

One logged, you get the response of the protected resources.

If you want intermediary resources, you can use an `[Options]` section :

```
GET https://foo.com
[Options]
# Save the response to an intermediary file
output: foo.bin

GET https://bar.com
[Options]
# Display response to standard output
output: -
```

Or you can write a request by file and then you will get all responses on standard output.

```shell
$ hurl foo.hurl bar.hurl baz.hurl
```

If you want to just test some requests and are not interested with the response, you can use [`--test`](https://hurl.dev/docs/running-tests.html):

```
$ hurl --test *.hurl
```

I'm closing the issue, feel free to open a discussion or proposed an issue for any new feature!

**Closed by jcamiel** 2024-05-04 13:56 UTC
Labels: bug
