### ISSUE TITLE
add the --parallel option to run *.hurl files in parallel instead of sequentially

### ISSUE THREAD

**Issue by lepapareil** [Orange-OpenSource/hurl#87] opened 2020-11-20 18:28 UTC
Hi guys 😄 

Currently when I launch this command

```bash
hurl a.hurl b.hurl c.hurl
```

hurl runs each `*.hurl` file sequentially, first a.hurl, then b.hurl, then c.hurl.

```bash
# tests started sequentially
hurl a.hurl b.hurl c.hurl

─ BEGIN
       ├─ a.hurl
                ├─ b.hurl
                         ├─ c.hurl
─ END
```

I propose you to add the `--parallel` option allowing hurl to run `*.hurl` files in parallel:

```bash
# all tests started at same time
hurl --parallel a.hurl b.hurl c.hurl

─ BEGIN
      ├─ a.hurl ├─ b.hurl ├─ c.hurl
─ END
```

```bash
# tests started two at a time
hurl --parallel 2 a.hurl b.hurl c.hurl

─ BEGIN
       ├─ a.hurl  ├─ b.hurl
       ├─ c.hurl
─ END
```

What do you think about it?

**Comment by fabricereix** [comment] 2020-11-21 16:50
This feature could be indeed be useful in order to reduce the total test duration. It does not impact the hurl format and any existing semantics. It can not be implemented for the next release but maybe one after.

**Comment by lepapareil** [comment] 2020-11-21 19:33
Great news :)

**Comment by gbourne1** [comment] 2022-12-20 16:00
Was about to open this feature request. Hurl has been great and as the number of .hurl files grows it would be great to run them in parallel.

**Comment by jcamiel** [comment] 2022-12-20 17:10
Yes! On 2023, the big features we plan to work on:

1. IDE support (starting with VSCode)
2. this feature (launch test in parallel)
3. Official apt support

We're going to work in this order as 1. might force us to rewrite the parser code. The parallel thing is (in my mind at least) one of the main feature we should address (it's in our mind since the begining, practically one of the first issues submitted). It's really adapted to a CLI tool like Hurl. We're using Hurl daily ourselves and I'm sure the parallel tests are going not only to improve tests duration but also find bugs on our web app / APIs.

**Comment by muffl0n** [comment] 2023-05-02 09:49
Workaround I'm using
```
parallel -j $(ls -1 *.hurl | wc -l) -i sh -c "hurl {} --test" -- *.hurl
echo "retval: $?"
```
Spawns one process for each file matching `*.hurl`. The output is not perfect, cause you have to find the error output somewhere in the overall output. But it boosts our CI run quite nice from several minutes to some seconds.

**Comment by jcamiel** [comment] 2023-05-02 10:22
Yes, we're really going to take inspiration on `parallel` to implement these features

**Comment by indy-singh** [comment] 2023-07-11 20:33
Was just about to raise this feature request myself. I'm investigating deprecating our Runscope suite and migrating to Hurl and this would be a killer feature! <3

**Comment by jcamiel** [comment] 2023-07-11 20:38
It's a high priority in our todo list!

**Comment by muffl0n** [comment] 2023-07-12 04:56
Would love to to some alpha testing. Let me know if I can be of any help!

**Comment by jcamiel** [comment] 2023-11-06 16:52
Initialisation of an architecture document here => [/docs/spec/runner/parallel.md](https://github.com/Orange-OpenSource/hurl/blob/master/docs/spec/runner/parallel.md)

**Comment by jcamiel** [comment] 2024-02-04 12:17
@lepapareil @fabricereix I've done some initial work about how we could render `hurl --test` while running in parallel => doc here <https://github.com/Orange-OpenSource/hurl/blob/master/docs/spec/runner/parallel.md#--test-output> and proto (asciinema) here => <https://jcamiel.github.io/parallel/>. For discussion

**Comment by jcamiel** [comment] 2024-02-08 12:24
<https://jcamiel.github.io/parallel/> parallel console output after discussion with @lepapareil / @fabricereix

**Comment by muffl0n** [comment] 2024-04-04 20:36
My first test looks amazing! I ran our 2520 tests (in 20 files) and the results speak for themselves:
* default (non-parallel) execution: 48s
* parallel execution, 1 job per file: 8s

I chose to run 1 job per file cause the default
> By default, the size is roughly the number of available CPUs.

is too conservative in my opinion. My underpowered test VM only has 1 CPU, so it would use one thread. But it shows that it can easily manage the 20 jobs I use in my test.

Tap, junit and html reports look good and in order. 

Gonna give it a try in our CI tomorrow, but I do not expect any problems here.

Thank you very much! This is just awesome! ❤️‍🔥 

PS: I built a docker image for my test if anyone has the need: https://github.com/users/muffl0n/packages/container/package/hurl

**Comment by jcamiel** [comment] 2024-04-04 20:45
> I chose to run 1 job per file cause the default
> is too conservative in my opinion

Good feedback, we'll certainly adjust it

**Comment by infogulch** [comment] 2024-04-04 22:21
Old school async: dump a bunch of threads on the OS and let the scheduler handle it 🤷. I could be going out on a limb here, but I doubt curl's C api was designed to work with a rust async scheduler, and I'd guess that shoehorning it would be non-trivial to say the least. So I'm glad that throwing threads at it seems to work. 👍

**Comment by muffl0n** [comment] 2024-04-05 07:16
My tests in our CI also went well: Reports are displayed/parsed like before.

**Comment by jcamiel** [comment] 2024-04-05 08:22
Thanks a lot for the tests @muffl0n , do you get speed improvement in your CI as well?

**Comment by muffl0n** [comment] 2024-04-05 09:53
Yes, the speedup is about the same as in my previous tests.

**Comment by jcamiel** [comment] 2024-04-23 08:07
I'm closing this issue, we'll open new, more specific issues from now.

**Closed by jcamiel** 2024-04-23 08:07 UTC
Labels: enhancement, topic: parallel
